name: etc-spec
author: open-source@roman-gonzalez.info

dependencies:
  - aeson
  - aeson-better-errors
  - base
  - directory
  - filepath
  - prettyprinter
  - rio
  - scientific
  - template-haskell
  - transformers
  - yaml

library:
  source-dirs: src
  exposed-modules:
  - Etc
  # Internal API
  - Etc.Internal.Config
  - Etc.Internal.Config.TH
  - Etc.Internal.FileFormat
  - Etc.Internal.Resolver.Types
  - Etc.Internal.Resolver.File
  - Etc.Internal.Resolver.File.Types
  - Etc.Internal.Resolver.File.Error
  - Etc.Internal.Spec.Parser
  - Etc.Internal.Spec.Serializer
  - Etc.Internal.Spec.Types
  - Etc.Internal.CustomType
  # Public API
  - Etc.Resolver
  - Etc.Spec

tests:
  etc-spec-tests:
    main: TestSuite.hs
    source-dirs: test
    dependencies:
      - aeson-qq
      - raw-strings-qq
      - base
      - hspec
      - QuickCheck
      - rio

      - etc-spec
