name: etc-spec
author: open-source@roman-gonzalez.info

dependencies:
  - aeson
  - aeson-better-errors
  - base
  - rio
  - template-haskell
  - prettyprinter

library:
  source-dirs: src
  exposed-modules:
  - Etc.Spec
  - Etc.Spec.Internal.Parser
  - Etc.Spec.Internal.Types

tests:
  etc-spec-tests:
    main: TestSuite.hs
    source-dirs: test
    dependencies:
      - base
      - rio
      - etc-spec
      - aeson-qq
      - hspec
